name: Apply Deployments

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [deployment]

jobs:
  teste:
    name: Apply Deployments
    runs-on: ubuntu-latest
    
    steps:
      - name: AWS Deployment
        run: echo "Deploying..."
