name: Apply Deployments

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Apply Deployments
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello World
        run: echo "Hello, world! This is a message from the GitHub Action."
