name: Apply Deployments

on:
  repository_dispatch:
    types: [trigger-eks-deployment]
  workflow_dispatch:

jobs:
  teste:
    name: Apply Deployments
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello World
        run: echo "Hello, world! This is a message from the GitHub Action."
