name: Sonar analysis

on:
  repository_dispatch:
    types:
      - trigger-eks-deployment

jobs:
  build:
    name: teste
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        run: echo "Hello"
